export const FAMILY_FILL: Record<string, string> = {
  ALKALI_METAL: "#FACE9E",
  ALKALINE_EARTH: "#F9E495",
  TRANSITION_METAL: "#A8D5F5",
  POST_TRANSITION_METAL: "#CFDCEA",
  METALLOID: "#BCDEA6",
  REACTIVE_NONMETAL: "#F8BAC8",
  HALOGEN: "#9FDFD2",
  NOBLE_GAS: "#C5B0F5",
  LANTHANIDE: "#F7C0B9",
  ACTINIDE: "#B5E6B2",
  EXOTIC_THEORETICAL: "#F2F7FC",
};
