export const FAMILY_FILL: Record<string, string> = {
  ALKALI_METAL: "#F8D6B3",
  ALKALINE_EARTH: "#F6E3A1",
  TRANSITION_METAL: "#B9DDF3",
  POST_TRANSITION_METAL: "#DCE3EB",
  METALLOID: "#C4DDBC",
  REACTIVE_NONMETAL: "#F5C6D0",
  HALOGEN: "#BDE4DB",
  NOBLE_GAS: "#C9B6F5",
  LANTHANIDE: "#F6C2B7",
  ACTINIDE: "#C8E6BF",
  EXOTIC_THEORETICAL: "#F2F7FC",
};
