export const FAMILY_FILL: Record<string, string> = {
  ALKALI_METAL: "#F7AE5E",
  ALKALINE_EARTH: "#F5D24E",
  TRANSITION_METAL: "#6EB9EE",
  POST_TRANSITION_METAL: "#AFC4DC",
  METALLOID: "#8FC86A",
  REACTIVE_NONMETAL: "#F48CA4",
  HALOGEN: "#5FC9B4",
  NOBLE_GAS: "#9F7BEF",
  LANTHANIDE: "#F2968A",
  ACTINIDE: "#83D57F",
  EXOTIC_THEORETICAL: "#F2F7FC",
};
